version: "3.8"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  agixt:
    image: joshxt/agixt:${AGIXT_VERSION:-main}
    init: true
    depends_on:
      - db
    environment:
      - UVICORN_WORKERS=4
      - TOKENIZERS_PARALLELISM=False
    ports:
      - "8501:8501"
      - "7437:7437"
    volumes:
      - ./agixt:/agixt:rw
      - ./streamlit:/streamlit:rw
      - ./tests:/tests:rw
      - ./models:/model:rw
